FROM hypriot/rpi-alpine:3.4 

ADD . /go-ethereum

RUN \
  apk add --update git go make gcc musl-dev         && \
  apk add ethereum && \
  apk del git go make gcc musl-dev                  && \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*

EXPOSE 8545
EXPOSE 30303

ENTRYPOINT ["/geth"]
